### ISSUE TITLE
Edit a task

### ISSUE THREAD

**Issue by DevTony101** [DevTony101/js-todo-app-indexed_db#1]
Add the ability to edit any given task.

**Comment by shobhi1310** [comment]
can I work on this issue, if so please do assign me this issue.

**Comment by shobhi1310** [comment]
Just a side question, what does the reset button do ?

**Comment by DevTony101** [comment]
The reset button "reset" the form.

Every new task created _should_ have an edit button. The means that allow a user edit said task is up to you, it can be trough a modal window or replacing the text inside the task with an input tag, etc.

**Comment by shobhi1310** [comment]
Modal seems a better option in terms of UI/UX

**Comment by shobhi1310** [comment]
![image](https://user-images.githubusercontent.com/42507632/97077878-e43fd180-1604-11eb-9a70-30d4c2663658.png)

For saving we have the `.add()`, for updating the same task by key what function needs to be used, I used `.put()` but it was not working as desired.

**Comment by shobhi1310** [comment]
@DevTony101 
sir, do review my PR once.
