### ISSUE TITLE
relocate edit button

### ISSUE THREAD

**Issue by shobhi1310** [DevTony101/js-todo-app-indexed_db#6]
## Description
Edit button needs to be shifted to left so that extra space is not consumed.
## Reproducing issue
- Use this [link](https://indexed-todo-app.netlify.app/)
- Create any task
- Look for the created task below and the corresponding edit button

## Screenshot
![image](https://user-images.githubusercontent.com/42507632/97165564-ebecab00-17a9-11eb-80f6-a6662f0e2590.png)

## Desired Change
![image](https://user-images.githubusercontent.com/42507632/97165871-5f8eb800-17aa-11eb-9f49-5c864e881dc9.png)

- Color of edit button can be modified.

**Comment by tremby** [comment]
Can you give more detail? A screenshot and mockup of what you want, maybe?

**Comment by Charliiee** [comment]
Can I take this one?
