### ISSUE TITLE
"gray out" a completed task

### ISSUE THREAD

**Issue by DevTony101** [DevTony101/js-todo-app-indexed_db#9]
Currently, when the user marks a task as "complete", the only changes on the UI is that the content text of the task gets a line through. A more impactful change needs to be done, changing the color of the panel to a more darker one seems appropiate.

**Comment by simonhoyos** [comment]
Hey @DevTony101 I can help you with this one!

**Comment by simonhoyos** [comment]
A PR is now opened. Let me know if I must make any changes or any improvements
